### ISSUE TITLE
ReferenceError: ReadableStream is not defined

### ISSUE THREAD

**Issue by dineshkumar14062001** [ultimateakash/puppeteer-html-pdf#12]
ReferenceError: ReadableStream is not defined
    at getReadableFromProtocolStream (/home/nanonino/lms/star-academy-content/node_modules/puppeteer-core/lib/cjs/puppeteer/common/util.js:241:5)
    at CdpPage.createPDFStream (/home/nanonino/lms/star-academy-content/node_modules/puppeteer-core/lib/cjs/puppeteer/cdp/Page.js:853:66)
    at async CdpPage.pdf (/home/nanonino/lms/star-academy-content/node_modules/puppeteer-core/lib/cjs/puppeteer/cdp/Page.js:857:26)
    at async PuppeteerHTMLPDF.generatePDF (/home/nanonino/lms/star-academy-content/node_modules/puppeteer-html-pdf/lib/index.js:160:18)
    at async PuppeteerHTMLPDF.create (/home/nanonino/lms/star-academy-content/node_modules/puppeteer-html-pdf/lib/index.js:48:23)
    at async /home/nanonino/lms/star-academy-content/routes/services/common-service.js:764:33
    
    const puppeteerHtmlToPdf = require('puppeteer-html-pdf');
let htmlPDF = new puppeteerHtmlToPdf();

                let option = {
                    format: "A4",
                    margin: {
                        top: '1in',
                        right: '0.1in',
                        bottom: '0in',
                        left: '0.1in',
                    },
                    displayHeaderFooter: true,
                    footerTemplate: footerTpl,
                    headerTemplate: headerTpl,
                    args: ['--no-sandbox', '--disable-setuid-sandbox', '--disable-gpu'],                   
                }

                htmlPDF.setOptions(option);

                let pdfBuffer = await htmlPDF.create(htmlContent);
    
    node v-16
    how to solve this issue

**Comment by ultimateakash** [comment]
Hello @dineshkumar14062001 ,

It appears that you're using puppeteer-html-pdf v4, which might not be compatible with Node.js version 16. To resolve the issue, you can downgrade to version 3 of puppeteer-html-pdf:
Remove V4
```bash
npm remove puppeteer-html-pdf
```
Install V3
```bash
npm install puppeteer-html-pdf@3.x
```
Please check and let me know.

**Comment by dineshkumar14062001** [comment]
Its working fine thank you.
